services:
  portfolio:
    container_name: portfolio
    image: oliverrknox/portfolio:latest
    environment:
      GITHUB_OAUTH: example.token
    ports:
      - 8081:8080
    restart: unless-stopped