services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: hi@oliverknox.io
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5454:80
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: